defmodule UnionFormRepro.Repo.Migrations.AddCredentials do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_sqlite.generate_migrations`
  """

  use Ecto.Migration

  def up do
    create table(:credentials, primary_key: false) do
      add :access, :map, null: false
      add :id, :uuid, null: false, primary_key: true
    end
  end

  def down do
    drop table(:credentials)
  end
end